name: 'Prepare NodeJS'
description: 'Prepare nodejs'

runs:
  using: 'composite'
  steps:
    - name: set node version
      shell: bash
      run: echo "NODE_VERSION=$(./ci-scripts/tool-version.sh nodejs)" >> "$GITHUB_ENV"
    - uses: pnpm/action-setup@v3
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
