name: ci

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shared/prepare-ruby
      - uses: ./.github/actions/shared/prepare-nodejs
      - name: check formatting
        run: go lib:formatting:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shared/prepare-ruby
      - uses: ./.github/actions/shared/prepare-nodejs
      - name: lint
        run: go lib:lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shared/prepare-ruby
      - uses: ./.github/actions/shared/prepare-nodejs
      - name: run tests
        run: rake lib:test

  build:
    needs: [check-formatting, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shared/prepare-ruby
      - uses: ./.github/actions/shared/prepare-nodejs
      - name: build
        run: rake lib:build

  pre-release:
    environment: pre-release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shared/prepare-ruby
      - uses: ./.github/actions/shared/prepare-nodejs
      - name: configure-git
        run: ./ci-scripts/configure-git.sh
      - name: pre-release
        run: ./ci-scripts/pre-release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_JS_ACCESS_TOKEN }}
