name: Halboy TS

on:
  push:
    branches: ['main']

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-ruby
      - uses: ./.github/actions/prepare-nodejs
      - name: check formatting
        run: ./go lib:formatting:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-ruby
      - uses: ./.github/actions/prepare-nodejs
      - name: lint
        shell: bash
        run: ./go lib:lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-ruby
      - uses: ./.github/actions/prepare-nodejs
      - name: run tests
        shell: bash
        run: ./go lib:test

  build:
    needs: [check-formatting, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-ruby
      - uses: ./.github/actions/prepare-nodejs
      - name: build
        shell: bash
        run: ./go lib:build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: build
          path: build

  pre-release:
    environment: pre-release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - uses: ./.github/actions/prepare-ruby
      - uses: ./.github/actions/prepare-nodejs
      - name: configure-git
        run: ./ci-scripts/configure-git.sh
      - name: pre-release
        run: ./ci-scripts/pre-release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_JS_ACCESS_TOKEN }}
